title: Tailwind Jekyll Starter Kit
description: A starter kit for using Tailwind with Jekyll

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
  - netlify.toml

defaults:
  - scope:
      path: "assets/imgs"
    values:
      image: true